### ISSUE TITLE
F-Droid QR Code broken

### ISSUE THREAD

**Issue by Artim96** [Depau/fdroid_shizuku_privileged_extension#2]
I just tried adding the repo to F-Droid, but I noticed that can't work. The url in the code points to localhost. So no way anything can be found there.

**Comment by Imold** [comment]
I downloaded it from https://github.com/depau/fdroid_shizuku_privileged_extension/raw/master/fdroid/repo/F-DroidShizukuPrivilegedExtension-release.apk

**Comment by Artim96** [comment]
@Imold hope you realize your comment kinda misses the point.

The readme tells you to go to a website and add a repo from there, which is just impossible. So either the QR Code or the readme need to be fixed.

Your kink may help other people, but since the extension is broken right now and at least for the moment abandoned - and especially since F-Droid by now actually has added the new APIs to update its own apps (afaik at least if they meet the target SDK level requirements or whatever) this extension maybe just should be marked as archived.
